sudo: requiered
services:
    - docker

before_install:
    - docker build -t elerno/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true elerno/react-test npm test

after_success:
    - docker build -t elerno/multi-client ./client
    - docker build -t elerno/multi-nginx ./nginx
    - docker build -t elerno/multi-server ./server
    - docker build -t elerno/multi-worker ./worker
    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push elerno/multi-client
    - docker push elerno/multi-nginx
    - docker push elerno/multi-server
    - docker push elerno/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-997739507955
    bucket_path: docker-multi

    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY